server:
  port: 8061

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
     rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

management:
  security:
    enabled: false
